Failure # 1 (occurred at 2021-07-28_15-05-19)
Traceback (most recent call last):
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/worker.py", line 1495, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=37551, ip=10.204.3.65)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=37551, ip=10.204.3.65)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 340, in _inner
    inner(config, checkpoint_dir=None)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 331, in inner
    trainable(config, **fn_kwargs)
  File "tune_hyperparameters_robin.py", line 41, in train_segmentation
    trainer.fit(lit_model, data)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 967, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/cluster/home/samuelbe/rosas_road_segmentation/common/lightning/base.py", line 70, in validation_step
    y_hat = self.model(x)
  File "/cluster/apps/python/3.8.5_gpu_gcc820/x86_64/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/samuelbe/rosas_road_segmentation/models/transunet/vit_seg_modeling.py", line 389, in forward
    x, attn_weights, features = self.transformer(x)  # (B, n_patch, hidden)
  File "/cluster/apps/python/3.8.5_gpu_gcc820/x86_64/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/samuelbe/rosas_road_segmentation/models/transunet/vit_seg_modeling.py", line 254, in forward
    embedding_output, features = self.embeddings(input_ids)
  File "/cluster/apps/python/3.8.5_gpu_gcc820/x86_64/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/samuelbe/rosas_road_segmentation/models/transunet/vit_seg_modeling.py", line 160, in forward
    embeddings = x + self.position_embeddings
RuntimeError: The size of tensor a (625) must match the size of tensor b (256) at non-singleton dimension 1

