Failure # 1 (occurred at 2021-07-28_12-06-02)
Traceback (most recent call last):
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/worker.py", line 1495, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=30735, ip=10.204.3.65)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=30735, ip=10.204.3.65)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 340, in _inner
    inner(config, checkpoint_dir=None)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/utils/trainable.py", line 331, in inner
    trainable(config, **fn_kwargs)
  File "tune_hyperparameters_lucas2.py", line 17, in train_segmentation
    model = get_model(model_name, config)
  File "/cluster/home/samuelbe/rosas_road_segmentation/common/get_model.py", line 25, in get_model
    model = VisionTransformer(transunet_config, img_size=config['patch_size'], num_classes=transunet_config.n_classes)
  File "/cluster/home/samuelbe/rosas_road_segmentation/models/transunet/vit_seg_modeling.py", line 376, in __init__
    self.transformer = Transformer(config, img_size, vis)
  File "/cluster/home/samuelbe/rosas_road_segmentation/models/transunet/vit_seg_modeling.py", line 250, in __init__
    self.embeddings = Embeddings(config, img_size=img_size)
  File "/cluster/home/samuelbe/rosas_road_segmentation/models/transunet/vit_seg_modeling.py", line 134, in __init__
    n_patches = (img_size[0] // patch_size_real[0]) * (img_size[1] // patch_size_real[1])
ZeroDivisionError: integer division or modulo by zero

