Failure # 1 (occurred at 2021-07-21_14-30-39)
Traceback (most recent call last):
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/samuelbe/.local/lib/python3.8/site-packages/ray/worker.py", line 1497, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

